##Broadlink switches
- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  switches:
    bedroom_tv:
      friendly_name: 'Bedroom TV'
      command_on: 'JgCQAAABKpMTERM2FBETNhMSEzYTNhQ2EzYTNhQ2ExETEhMREzYUNhM2EzYUNhMREzYUERMRFBETERMSExETNhQREzYTNhQ2EwAE4wABKpITEhM2ExEUNhMREzYUNhM2EzYUNhM2ExITERMSEzYTNhM3EzYTNhQREzYTEhMREzYTEhMRExITNhMRFDYTNhMRFAANBQAAAAAAAAAA'
      command_off: 'JgCQAAABKpMTERM2FBETNhMSEzYTNhQ2EzYTNhQ2ExETEhMREzYUNhM2EzYUNhMREzYUERMRFBETERMSExETNhQREzYTNhQ2EwAE4wABKpITEhM2ExEUNhMREzYUNhM2EzYUNhM2ExITERMSEzYTNhM3EzYTNhQREzYTEhMREzYTEhMRExITNhMRFDYTNhMRFAANBQAAAAAAAAAA'
    tv_up_down:
      friendly_name: 'TV Up and Down'
      command_on: 'JgCQAAABLJIUERM2FBEUNhMRFDYTNhQ2FDYTNhQ2ExITERQREzYUNhQ2ExEUERM2FDYUERMRFBETERQ2FDYTERQREzYUNhQ2EwAE5gABLJMUERM2FBETNhQRFDYTNhQ2FDYTNhQ2ExITERQREzYUNhQ2ExEUERM2FDYUERMRFDYTEhM2FDYTERQRFDYTNhQREwANBQAAAAAAAAAA'
      command_off: 'JgCQAAABK5MUERM2FBETNxMRFDYTNhQ2FDYTNhQ2ExITERQREzYUNhM2FDYUERMRFDYTNxMRFBETERQREzYUNhQRExEUNhM2FAAE5gABLJMTERQ2ExITNhQREzYUNhM3EzYUNhM3ExEUERMRFDYTNxM2FDYTEhMRFDYTNhQRFDYTERQREzcTNhQRExEUNhMSEwANBQAAAAAAAAAA'
    tv_left_right:
      friendly_name: 'TV Left and Right'
      command_on: 'JgCQAAABK5MTEhM2FBETNhQREzcTNhQ2EzYUNhM3ExEUERMSEzYTNxMRFDYTNhQ2EzcTERQRExITNhMSExEUERMSEzYTNxM2FAAE5gABLJIUERQ2ExEUNhMSEzYUNhM3EzYUNhM2FBETEhMRFDYTNxMRFDYTNhQ2EzcTERQREzcTNhQRExITERMSEzYUNhMSEwANBQAAAAAAAAAA'
      command_off: 'JgCQAAABK5MTEhM2ExITNhQREzcTNhM3EzYUNhM3ExETEhMRFDYTNxM2FBETNhQ1FBITNhQRExITERM3ExEUERM2FBETNxM2FAAE5gABK5MUERM3ExEUNhMSEzYUNhM2FDYTNxM2FBETEhMREzcTNhQ2ExITNhQ2ExITNhMSEzYUERM3ExEUERM3ExETNxMRFAANBQAAAAAAAAAA'
    tv_ok_back:
      friendly_name: 'TV OK and Back'
      command_on: 'JgCQAAABK5MUERM2FBETNxMRFDYTNhQ2EzcTNhQ2ExITERMSEzYUNhMSEzYTEhM2FBETNhQRExITNhQREzcTERM3ExEUNhM2FAAE5wABK5MUERM2FBETNxMRFDYTNxM2FDYTNxM2FBETEhMREzcTNhQREzcTERQ2ExITNhQREzYUNhMSEzYUERM3ExEUNhMSEwANBQAAAAAAAAAA'
      command_off: 'JgCQAAABLJIUERQ2ExEUNhMRFDYTNxM2FDYTNhQ2ExITERQREzYUNhMRFDYUNhMRFBETNhQ2FBETNhQRExEUNhQ2ExEUERM2FAAE5gABLJMTERQ2ExEUNhQREzYUNhM3EzYUNhM2FBEUERMRFDYTNhQRFDYTNhQRFBETNhQ2EzYUNhQRExEUNhQ2ExEUERMTEgANBQAAAAAAAAAA'
    # bedroom_netflix:
      # friendly_name: 'Bedroom Netflix'
      # command_on: ' JgCQAAABK5MTEhM2FBETNhQREzcTNhM3EzYUNhM3ExEUERMRFDYTNxMREzcTERQREzcTERM3ExEUNhMSEzYTNxMRFDYTEhM2EwAE5wABK5MUERM2FBETNhQREzcTNhQ2EzcTNhQ2ExITERMSEzYUNhMSEzYTEhMRFDYTEhM2EzcTNhQREzcTNhQREzYUERMSEwANBQAAAAAAAAAA'
      # command_off: 'JgCQAAABKpMTERM2FBETNhMSEzYTNhQ2EzYTNhQ2ExETEhMREzYUNhM2EzYUNhMREzYUERMRFBETERMSExETNhQREzYTNhQ2EwAE4wABKpITEhM2ExEUNhMREzYUNhM2EzYUNhM2ExITERMSEzYTNhM3EzYTNhQREzYTEhMREzYTEhMRExITNhMRFDYTNhMRFAANBQAAAAAAAAAA'