homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 125.214
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customizations
  customize_domain: {}
  customize_glob: {}

#Simplisafe alarm
alarm_control_panel:
  platform: simplisafe
  username: !secret simplisafe_username
  password: !secret simplisafe_password

#Home Assistant automations
automation: !include_dir_merge_list automations

##Binary sensors
binary_sensor: !include_dir_merge_list binary_sensors

##Camera
camera:
  - platform: zoneminder

#Front-end config tool to adjust groups, views and z-wave settings
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#All device trackers
device_tracker:
  - platform: nmap_tracker
    hosts: !include nmap_ips.yaml
    track_new_devices: false
    interval_seconds: 30
    consider_home: 600
    home_interval: 10
    scan_options: " --privileged -sP "
  - platform: owntracks
    max_gps_accuracy: 100

# Discover some devices automatically
discovery:

#Emulated Hue configuration
emulated_hue:
  host_ip: !secret emulated_hue_ip
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - fan

#MQTT fan
fan: !include fan.yaml

# Enables the frontend
frontend:

# All groups and views
group: !include groups.yaml

# Enables support for tracking state changes over time.
history:

# Front end and API
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  use_x_forwarded_for: True
  trusted_networks: !secret home_ip_range
  ip_ban_enabled: True
  login_attempts_threshold: 3

# View events in a logbook
logbook:
  exclude:
    domains:
      - sun
      - sensor
      - binary_sensor
      - group

#Media Players
media_player:
  - platform: cast
  - platform: plex
  - platform: roku

# MQTT servers
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant-1

#Notification services  
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_key
    gcm_sender_id: !secret gcm_id

#Where and how long to store history
recorder:
  purge_days: 5
  db_url: !secret mysql_url
#Scenes
scene: !include_dir_merge_list scenes

#Scripts
script: !include_dir_merge_named scripts

# Sensors
sensor: !include_dir_merge_list sensors

# Track the sun
sun:

# All switches 
switch: !include_dir_merge_list switches

# Text to speech
tts:
  platform: google

# Checks for available updates
updater:

#Zones
zone: !include zones.yaml

#ZoneMinder Cameras
zoneminder:
  host: !secret zm_ip_address
  username: !secret zm_username
  password: !secret zm_password

#Z-Wave
zwave:
  usb_path: /dev/zwave
  autoheal: true
  polling_interval: 30000
  device_config: !include zwave_device_config.yaml
  device_config_domain:
    light:
      refresh_value: true
      delay: 6
    switch:
      refresh_value: true
      delay: 6