- platform: mqtt
  name: 'Bedroom Fan'
  state_topic: '315mhz/state/fan/1'
  command_topic: '315mhz/control/fan/1'
  oscillation_state_topic: '315mhz/state/fan/1'
  speed_state_topic: '315mhz/state/fan/speed/1'
  speed_command_topic: '315mhz/control/fan/1'
  qos: 0
  payload_on: 1
  payload_off: 0
  payload_oscillation_on: 1
  payload_oscillation_off: 0
  payload_low_speed: 2
  payload_medium_speed: 3
  payload_high_speed: 4
  retain: true
  speeds:
    - low
    - medium
    - high