- platform: mqtt
  name: 'Bedroom Fan'
  command_topic: 'master/control/fan/1'
  state_topic: 'master/state'
  state_value_template: '{{ value_json.fanOn }}'
  oscillation_state_topic: 'master/state'
  oscillation_value_template: '{{ value_json.fanOn }}'
  speed_command_topic: 'master/control/fan/1'
  speed_state_topic: 'master/state'
  speed_value_template: '{{ value_json.fanSpeed }}'
  qos: 0
  payload_on: 1
  payload_off: 0
  payload_oscillation_on: 1
  payload_oscillation_off: 0
  payload_low_speed: 2
  payload_medium_speed: 3
  payload_high_speed: 4
  retain: true
  speeds:
    - low
    - medium
    - high