#Sensors

## Weather by Norwegian Meteorological Institute and the NRK
- platform: yr
  monitored_conditions:
    - symbol

##The weather forecast delivered by Dark Sky
- platform: darksky
  api_key: !secret darksky_api_key
  update_inverval: '00:05'
  monitored_conditions:
    - summary
    - icon
    - temperature
    - temperature_max
    - temperature_min
    - humidity
    - cloud_cover
    - precip_probability
    - nearest_storm_distance
    - precip_type
    - wind_speed
    - wind_bearing
    - hourly_summary
    - minutely_summary
    - daily_summary

#Tracks the moon cycle
- platform: moon

##Local date and time
- platform: time_date
  display_options:
    - date_time

##PLEX monitor
- platform: plex
  host: !secret plex_ip
  server: Pegasus
  username: !secret plex_username
  password: !secret plex_password

##System monitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: last_boot
    - type: since_last_boot
    - type: ipv4_address
      arg: ens160

##Monitors the current state of ZoneMinder including the number of events and the current state of the cameras
- platform: zoneminder

##MQTT Sensors
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom temperature'
  unit_of_measurement: '°F'
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom pressure'
  unit_of_measurement: 'mb'
  value_template: '{{ value_json.barometer }}'
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom light level'
  unit_of_measurement: '%'
  value_template: '{{ value_json.photoCell }}'