##MQTT Sensors
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom temperature'
  unit_of_measurement: '°F'
  value_template: '{{ value_json.temperature }}'
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom light level'
  unit_of_measurement: '%'
  value_template: '{{ value_json.photoCell }}'