##System monitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: last_boot
    - type: since_last_boot
    - type: ipv4_address
      arg: ens160