#MQTT Binary sensors
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom motion'
  value_template: '{{ value_json.pir }}'
  qos: 0
  payload_on: 1
  payload_off: 0
  device_class: motion