#MQTT Binary sensors
##Master Bedroom
- platform: mqtt
  state_topic: 'master/sensor'
  name: 'Bedroom motion'
  value_template: '{{ value_json.pir }}'
  qos: 0
  payload_on: 1
  payload_off: 0
  device_class: motion
##Kitchen
- platform: mqtt
  state_topic: 'kitchen/sensor'
  name: 'Kitchen motion'
  value_template: '{{ value_json.pir }}'
  qos: 0
  payload_on: 1
  payload_off: 0
  device_class: motion