##Turns off all lights 45 minutes after sunrise
- alias: All lights off 45 min after sunrise
  trigger:
    platform: sun
    event: 'sunrise'
    offset: '00:45:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.main_floor_lights
        state: 'on'
      - condition: state
        entity_id: group.all_upstairs_lights
        state: 'on'
      - condition: state
        entity_id: light.kitchen_sink_level_13_0
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.main_floor_lights
        - group.all_upstairs_lights
        - light.kitchen_sink_level_13_0

##Turns off the all lights at 10:00am on weekdays
- alias: All lights off weekdays 10am
  trigger:
    platform: time
    after: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: or
        conditions:
          - condition: state
            entity_id: group.main_floor_lights
            state: 'on'
          - condition: state
            entity_id: group.all_upstairs_lights
            state: 'on'
          - condition: state
            entity_id: light.kitchen_sink_level_13_0
            state: 'on'            
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.main_floor_lights
        - group.all_upstairs_lights
        - light.kitchen_sink_level_13_0