##Turns on back porch light at sunset
- alias: Back porch lights on sunset
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: switch.back_porch_switch_16_0
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.back_porch_switch_16_0

##Turns off back porch light at 10:30pm
- alias: Back porch lights off late night
  trigger:
    platform: time
    after: '22:30:00'
  condition:
    condition: state
    entity_id: switch.back_porch_switch_16_0
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.back_porch_switch_16_0

##Turns on back porch light at 6am
- alias: Back porch lights on early morning
  trigger:
    platform: time
    after: '06:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: switch.back_porch_switch_16_0
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.back_porch_switch_16_0

##Turns off back porch light at sunrise
- alias: Back porch lights off sunrise
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: state
    entity_id: switch.back_porch_switch_16_0
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.back_porch_switch_16_0

##Turns the basement stair lights off after 5 minutes during daylight hours
- alias: Timer downstairs hallway lights off daytime
  trigger:
    platform: state
    entity_id: switch.basement_stairs_switch_9_0
    state: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
    condition: state
    entity_id: sun.sun
    state: 'above_horizon'
  action:
    - service: switch.turn_off
      entity_id: switch.basement_stairs_switch_9_0

##Turns the basement stair lights off after 10 minutes at night time
- alias: Timer downstairs hallway lights off nighttime
  trigger:
    platform: state
    entity_id: switch.basement_stairs_switch_9_0
    state: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: switch.turn_off
      entity_id: switch.basement_stairs_switch_9_0