##Turns the basement stair lights off after 5 minutes during daylight hours
- alias: Basement Stair Lights Off day
  trigger:
    platform: state
    entity_id: switch.basement_stairs_switch_9_0
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
    condition: time
    after: '08:30:00'
    before: '15:59:59' 
  action:
    - service: homeassistant.turn_off
      entity_id: switch.basement_stairs_switch_9_0

##Turns the basement stair lights off after 15 minutes at night time
- alias: Basement Stair Lights Off night
  trigger:
    platform: state
    entity_id: switch.basement_stairs_switch_9_0
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
    condition: time
    after: '16:00:00'
    before: '08:29:59' 
  action:
    - service: homeassistant.turn_off
      entity_id: switch.basement_stairs_switch_9_0