#Bedroom light automations

##Motion activated bedroom lights if the room is too dark
- alias: Bedroom motion ceiling light
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_motion
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.bedroom_lights
        state: 'off'
      - condition: state
        entity_id: script.disable_motion
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.bedroom_light_level
        below: 25
      - condition: or
        conditions:
          - condition: time
            after: '8:00:00'
            before: '21:30:00'
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: '10:00:00'
            before: '22:00:00'
            weekday:
              - sat
              - sun
  action:
    - service: homeassistant.turn_on
      entity_id: group.bedroom_lights

##Turn bedroom lights off, if no motion is detected within 20 minutes
- alias: Bedroom lights off no motion
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_motion
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.bedroom_lights
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.bedroom_lights