#Bedroom fan automations

##If bedroom temperature is 74 and 76 degrees, and it is between 8:30pm and 9am and someone is home, turn bedroom fan on low
- alias: Fan on low night time
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: 73
    below: 76
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:30:00'
        before: '08:59:59'
      - condition: state
        entity_id: group.family
        state: 'home' 
  action:
    - service: script.turn_on
      entity_id: script.fan_low
      
##If bedroom temperature is above 76 and below 80 degrees, and it is between 8:30pm and 9am and someone is home, turn bedroom fan on medium
- alias: Fan on medium night time
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: 76
    below: 80
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:30:00'
        before: '08:59:59'
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.fan_medium

##If bedroom temperature is above above 80 degrees, and it is between 8:30pm and 9am and someone is home, turn bedroom fan on high
- alias: Fan on high night time
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: 80
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:30:00'
        before: '08:59:59'
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.fan_high

##If bedroom temperature is below 72 degrees, turn bedroom fan off
- alias: Fan off too cold
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: 30
    below: 72
  condition:
    condition: state
    entity_id: fan.bedroom_fan
    state: 'on' 
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom_fan

##If after 9:30am, turn fan off if it is on
- alias: Fan off
  trigger:
    platform: time
    after: '09:30:00'
  condition:
    condition: state
    entity_id: fan.bedroom_fan
    state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom_fan