##Turns kitchen sink light, 40 minutes before sunset, if Patrick or Carla is home
- alias: Sink nightlight on sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:40:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: light.kitchen_sink_level_13_0
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_nightlight

##Turn sink light on 100% brightness with kitchen lights
- alias: Sink light on when kitchen lights on
  trigger:
    platform: state
    entity_id: light.kitchen_level_12_0
    from: 'off'
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_sink_light_on

##Turn kitchen sink light to nightlight when kitchen lights turn off
- alias: Sink nightlight on when kitchen lights off nighttime
  trigger:
    platform: state
    entity_id: light.kitchen_level_12_0
    from: 'on'
    to: 'off'    
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_nightlight

##Turn kitchen sink light off when kitchen lights turn off during daylight
- alias: Sink light off when kitchen lights off daytime
  trigger:
    platform: state
    entity_id: light.kitchen_level_12_0
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'above_horizon' 
  action:
    - service: light.turn_off
      entity_id: light.kitchen_sink_level_13_0

##Turns kitchen sink light off 2am
- alias: Sink light off late night
  trigger:
    platform: time
    after: '02:00:00'
  condition:
    condition: state
    entity_id: light.kitchen_sink_level_13_0
    state: 'on'        
  action:
    - service: light.turn_off
      entity_id: light.kitchen_sink_level_13_0

##Turns kitchen sink nightlight on 6am
- alias: Sink nightlight on morning
  trigger:
    platform: time
    after: '06:00:00'
  condition:
    condition: state
    entity_id: light.kitchen_sink_level_13_0
    state: 'off'        
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_nightlight

##Turns off all kitchen and dining lights 45 minutes after sunrise
- alias: All kitchen lights off sunrise
  trigger:
    platform: sun
    event: 'sunrise'
    offset: '00:45:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.kitchen_and_dining
        state: 'on'
      - condition: state
        entity_id: light.kitchen_sink_level_13_0
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.kitchen_and_dining
        - light.kitchen_sink_level_13_0