##Turns on living room lights, 40 minutes before sunset, if family is home
- alias: Hallway lights on sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:40:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: light.hallway_level_14_0
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hallway_level_14_0

##Turns off the main floor lights at 10:00am on weekdays
- alias: Main floor lights off weekdays 10am
  trigger:
    platform: time
    after: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: group.main_floor_lights
        state: 'on'        
  action:
    - service: homeassistant.turn_off
      entity_id: group.main_floor_lights

##Turn off main floor lights on weekdays, between 10am and 4pm, after being on for 10 minutes
- alias: Main floor lights work day timer
  trigger:
    platform: state
    entity_id: group.main_floor_lights
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
    condition: time
    after: '10:00:00'
    before: '16:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: homeassistant.turn_off
      entity_id: group.main_floor_lights

##Turn off main floor lights on weekdays, between 9:20pm and 4am, after being on for 15 minutes
- alias: Main floor lights weekday night time timer
  trigger:
    platform: state
    entity_id: group.main_floor_lights
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
      condition: time
      after: '21:20:00'
      before: '04:00:00'
      weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
  action:
    - service: homeassistant.turn_off
      entity_id: group.main_floor_lights