##Notifies when Home Assistant updates are available       
- alias: Notify HA update available
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.html5
    data_template:
      message: 'Version {{ states.updater.updater.state }} now available'

##Notifies when Carla gets to work
- alias: Notify Carla at work
  trigger:
    platform: zone
    entity_id: device_tracker.carla_note4
    zone: zone.carla_work
    event: 'enter'
  action:
    service: notify.html5
    data:
      message: 'Carla at work'
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        icon: '/local/carla.png'
        tag: 'carla'

##Notifies when Carla leaves work
- alias: Notify Carla left work
  trigger:
    platform: zone
    entity_id: device_tracker.carla_note4
    zone: zone.carla_work
    event: 'leave'
  action:
    service: notify.html5
    data:
      message: 'Carla left work'
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        icon: '/local/carla.png'
        tag: 'carla'

##Notifies when Carla gets home
- alias: Notify Carla at Home
  trigger:
    platform: zone
    entity_id: device_tracker.carla_note4
    zone: zone.home
    event: 'enter'
  action:
    service: notify.html5
    data:
      message: 'Carla is home'
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        icon: '/local/carla.png'
        tag: 'carla'

##Notifies when Patrick gets home
- alias: Notify Patrick at home
  trigger:
    platform: zone
    entity_id: device_tracker.patrick_pats7edge
    zone: zone.home
    event: 'enter'
  action:
    service: notify.html5
    data:
      message: 'Patrick is home'
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        icon: '/local/patrick.png'
        tag: 'patrick'

##Notifies when Patrick leaves home
- alias: Notify Patrick left home
  trigger:
    platform: zone
    entity_id: device_tracker.patrick_pats7edge
    zone: zone.home
    event: 'leave'
  action:
    service: notify.html5
    data:
      message: 'Patrick left home'
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        icon: '/local/patrick.png'
        tag: 'patrick'
##DHT failure master bedroom
- alias: Notify DHT failed master bedroom
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    below: 1
  condition:
    condition: template
    value_template: {{ trigger.from_state.state } <> { trigger.to_state.state }}
  action:
    service: notify.html5
    data_template:
      message: 'DHT failed bedroom - {{ trigger.from_state.state }}:{{ trigger.to_state.state }}'
    data:
      message: ''
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        tag: 'dht-master-bedroom'
##DHT failure kitchen
- alias: Notify DHT failed kitchen
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_temperature
    below: 1
  condition:
    condition: template
    value_template: {{ trigger.from_state.state } <> { trigger.to_state.state }}
  action:
    service: notify.html5
    data_template:
      message: 'DHT failed kitchen - {{ trigger.from_state.state }}:{{ trigger.to_state.state }}'
    data:
      message: ''
      target:
        - 'Pat S7 Edge'
        - 'Blackbird Chrome'
      data:
        tag: 'dht-kitchen'