##Turn off all upstairs lights at 9am on weekdays
- alias: Upstairs lights off weekday mornings
  trigger:
    platform: time
    after: '09:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_upstairs_lights
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_upstairs_lights

##Turns the up stairs hallway lights off after 5 minutes during daylight hours
- alias: Timer upstairs hallway lights off daytime
  trigger:
    platform: state
    entity_id: light.up_stairs_hallway_level_15_0
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
    condition: state
    entity_id: sun.sun
    state: 'above_horizon' 
  action:
    - service: light.turn_off
      entity_id: light.up_stairs_hallway_level_15_0

##Turns the up stairs hallway lights off after 15 minutes at night time
- alias: Timer upstairs hallway lights off nighttime  
  trigger:
    platform: state
    entity_id: light.up_stairs_hallway_level_15_0
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon' 
  action:
    - service: light.turn_off
      entity_id: light.up_stairs_hallway_level_15_0